CREATE TABLE [config].[adf_log]
(logId int identity(1,1),
dataFactory varchar(150),
pipelineName varchar(150),
pipelineRunId varchar(150),
sourceTable varchar(150),
destinationFolder varchar(150),
destinationFile varchar(150),
triggerTime date,
triggerName varchar(150),
triggerType varchar(50),
rowsRead int,
rowsCopied int,
throughPut decimal (15,1),
errors varchar(Max),
execution_Details_source_type varchar(150),
execution_Details_sink_type varchar(150),
execution_Details_status varchar(100),
effective_Integration_Runtime varchar(150),
used_Data_Integration_Units int,
billing_Reference_activity_Type varchar(150))
